# Generated by Django 4.1.3 on 2022-12-08 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soldiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarOr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baror_round', models.CharField(max_length=50, unique=True)),
                ('start_round_date', models.DateTimeField(blank=True, null=True)),
                ('stop_round_date', models.DateTimeField(blank=True, null=True)),
                ('baror_status', models.CharField(choices=[('Waiting for allocate', 'Waiting for allocate'), ('Ready', 'Ready'), ('Running', 'Running'), ('Done', 'Done')], default='Waiting for allocate', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BarorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('float_score', models.FloatField(blank=True, max_length=200, null=True)),
                ('str_score', models.CharField(blank=True, max_length=10, null=True)),
                ('baror_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baror.baror')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soldiers.soldier')),
            ],
        ),
    ]
