# Generated by Django 4.1.3 on 2022-11-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soldiers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarOr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baror_round', models.CharField(max_length=50)),
                ('start_round_date', models.DateField(blank=True, null=True)),
                ('soldiers', models.ManyToManyField(to='soldiers.soldier')),
            ],
        ),
        migrations.CreateModel(
            name='BarorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baror_score', models.DateField()),
                ('baror_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baror.baror')),
                ('soldier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soldiers.soldier')),
            ],
        ),
    ]
