# Generated by Django 4.1.3 on 2022-11-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baror', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baror',
            name='start_round_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='baror',
            name='stop_round_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barorscore',
            name='baror_score',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
