# Generated by Django 4.1.3 on 2022-11-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers', '__first__'),
        ('baror', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baror',
            name='soldiers',
            field=models.ManyToManyField(through='baror.BarorScore', to='soldiers.soldier'),
        ),
    ]
