# Generated by Django 4.1.2 on 2022-11-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baror', '0002_alter_baror_soldiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baror',
            name='baror_round',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
