# Generated by Django 4.1.3 on 2022-11-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baror', '0002_alter_baror_start_round_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barorscore',
            name='baror_score',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
