# Generated by Django 4.1.3 on 2022-11-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baror', '0003_alter_barorscore_baror_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barorscore',
            name='baror_score',
            field=models.FloatField(blank=True, max_length=200, null=True),
        ),
    ]
