# Generated by Django 4.1.3 on 2022-11-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baror', '0003_alter_baror_baror_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='baror',
            name='status',
            field=models.CharField(default='Waiting for soldiers', max_length=20),
        ),
    ]
