# Generated by Django 4.1.3 on 2022-11-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baror', '0004_alter_barorscore_baror_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barorscore',
            old_name='baror_score',
            new_name='float_score',
        ),
        migrations.AddField(
            model_name='barorscore',
            name='str_score',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
