# Generated by Django 4.1.3 on 2022-11-20 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baror', '0004_baror_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baror',
            old_name='status',
            new_name='baror_status',
        ),
    ]
