# Generated by Django 4.1.3 on 2022-12-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baror', '0005_rename_baror_score_barorscore_float_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baror',
            name='baror_status',
            field=models.CharField(choices=[('Waiting for allocate', 'Waiting for allocate'), ('Ready', 'Ready'), ('Running', 'Running'), ('Done', 'Done')], default='Waiting for allocate', max_length=20),
        ),
    ]
