# Generated by Django 4.1.3 on 2022-11-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baror', '0005_rename_status_baror_baror_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baror',
            name='soldiers',
        ),
        migrations.AlterField(
            model_name='barorscore',
            name='baror_score',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
