# Generated by Django 4.1.3 on 2022-11-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baror', '0006_remove_baror_soldiers_alter_barorscore_baror_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baror',
            name='baror_status',
            field=models.CharField(default='Waiting for allocate', max_length=20),
        ),
    ]
