# Generated by Django 4.1.3 on 2022-12-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idf_num', models.PositiveSmallIntegerField()),
                ('soldier_status', models.CharField(choices=[('Waiting for Shalishut', 'Waiting for Shalishut'), ('Waiting for Clinic', 'Waiting for Clinic'), ('Waiting for Baror', 'Waiting for Baror'), ('Ready to run', 'Ready to run'), ('Running', 'Running'), ('After Baror', 'After Baror'), ('Medically disqualified', 'Medically disqualified'), ('Active', 'Active'), ('Quit', 'Quit'), ('Pass', 'Pass')], default='Waiting for Shalishut', max_length=50)),
            ],
        ),
    ]
