# Generated by Django 4.1.3 on 2022-11-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='soldier_status',
            field=models.CharField(default='Waiting for Shalishut', max_length=50),
        ),
    ]
