# Generated by Django 4.1.3 on 2022-11-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='soldier_status2',
            field=models.CharField(default='Waiting for Baror', max_length=50),
        ),
    ]
