# Generated by Django 4.1.3 on 2022-11-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers', '0002_alter_soldier_soldier_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldier',
            name='idf_num',
            field=models.PositiveSmallIntegerField(default=9999, max_length=3),
            preserve_default=False,
        ),
    ]
