# Generated by Django 4.1.3 on 2022-11-29 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers', '0003_soldier_idf_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soldier',
            name='idf_num',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
