# Generated by Django 4.1.3 on 2022-12-08 20:50

import clinic.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soldiers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_declaration', models.FileField(max_length=254, upload_to=clinic.models.Clinic.user_directory_path)),
                ('clinic_status', models.CharField(choices=[('Fit', 'Fit'), ('Unfit', 'Unfit')], default='Fit', editable=False, max_length=50)),
                ('note', models.TextField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soldier', models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='soldiers.soldier')),
            ],
        ),
    ]
