# Generated by Django 4.1.3 on 2022-12-03 18:09

import clinic.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='note',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='health_declaration',
            field=models.FileField(max_length=254, upload_to=clinic.models.Clinic.user_directory_path),
        ),
    ]
