# Generated by Django 4.1.3 on 2022-11-30 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soldiers', '0004_alter_soldier_idf_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shalishut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_num', models.CharField(max_length=9)),
                ('soldier_name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('profile', models.IntegerField(choices=[(97, '97'), (82, '82'), (72, '72')])),
                ('shalishut_status', models.CharField(choices=[('Open', 'Open'), ('Done', 'Done')], default='Open', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soldier', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='soldiers.soldier')),
            ],
        ),
    ]
