# Generated by Django 4.1.3 on 2022-11-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shalishut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shalishut',
            name='shalishut_status',
            field=models.CharField(choices=[('Open', 'Open'), ('Done', 'Done')], default='Open', editable=False, max_length=50),
        ),
    ]
