# Generated by Django 4.1.3 on 2022-11-30 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers', '0005_alter_soldier_soldier_status'),
        ('shalishut', '0002_alter_shalishut_shalishut_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shalishut',
            name='soldier',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='soldiers.soldier', unique=True),
        ),
    ]
