# Generated by Django 4.1.3 on 2022-11-30 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soldiers', '0005_alter_soldier_soldier_status'),
        ('shalishut', '0003_alter_shalishut_soldier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shalishut',
            name='soldier',
            field=models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='soldiers.soldier'),
        ),
    ]
