# Generated by Django 4.1.3 on 2022-12-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shalishut', '0004_alter_shalishut_soldier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shalishut',
            name='soldier_name',
        ),
        migrations.AddField(
            model_name='shalishut',
            name='firsname',
            field=models.CharField(default='firstname', max_length=20),
        ),
        migrations.AddField(
            model_name='shalishut',
            name='lastname',
            field=models.CharField(default='lastname', max_length=20),
        ),
    ]
