# Generated by Django 4.1.3 on 2022-12-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shalishut', '0005_remove_shalishut_soldier_name_shalishut_firsname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shalishut',
            old_name='firsname',
            new_name='firstname',
        ),
    ]
